#[[<protocol><domain>/]<user>/<repo>:]<branch>[/subdir[/subsubdir[...]]]
#https://x-access-token:{environ.get('INPUT_TOKEN')}@

from pytest import mark

from btd.location import Location, ParseLocation


@mark.parametrize(
    "location, expected",
    [
        (
            'branch',
            Location(
                branch='branch'
            )
        ),
        (
            'branch/',
            Location(
                branch='branch'
            )
        ),
        (
            'branch/subdir',
            Location(
                branch='branch',
                subdirs=['subdir']
            )
        ),
        (
            'branch/subdir/',
            Location(
                branch='branch',
                subdirs=['subdir']
            )
        ),
        (
            'branch/subdir/subsubdir',
            Location(
                branch='branch',
                subdirs=['subdir','subsubdir']
            )
        ),
        (
            'branch/subdir/subsubdir/',
            Location(
                branch='branch',
                subdirs=['subdir','subsubdir']
            )
        ),
        (
            'user/repo:branch',
            Location(
                user='user',
                repo='repo',
                branch='branch'
            )
        ),
        (
            'user/repo:branch/',
            Location(
                user='user',
                repo='repo',
                branch='branch'
            )
        ),
        (
            'user/repo:branch/subdir',
            Location(
                user='user',
                repo='repo',
                branch='branch',
                subdirs=['subdir']
            )
        ),
        (
            'user/repo:branch/subdir/',
            Location(
                user='user',
                repo='repo',
                branch='branch',
                subdirs=['subdir']
            )
        ),
        (
            'user/repo:branch/subdir/subsubdir',
            Location(
                user='user',
                repo='repo',
                branch='branch',
                subdirs=['subdir','subsubdir']
            )
        ),
        (
            'user/repo:branch/subdir/subsubdir/',
            Location(
                user='user',
                repo='repo',
                branch='branch',
                subdirs=['subdir','subsubdir']
            )
        ),
        (
            'https://github.com/user/repo:branch',
            Location(
                protocol='https',
                domain='github.com',
                user='user',
                repo='repo',
                branch='branch',
            )
        ),
        (
            'https://github.com/user/repo:branch/',
            Location(
                protocol='https',
                domain='github.com',
                user='user',
                repo='repo',
                branch='branch',
            )
        ),
        (
            'https://github.com/user/repo:branch/subdir',
            Location(
                protocol='https',
                domain='github.com',
                user='user',
                repo='repo',
                branch='branch',
                subdirs=['subdir']
            )
        ),
        (
            'https://github.com/user/repo:branch/subdir/',
            Location(
                protocol='https',
                domain='github.com',
                user='user',
                repo='repo',
                branch='branch',
                subdirs=['subdir']
            )
        ),
        (
            'https://github.com/user/repo:branch/subdir/subsubdir',
            Location(
                protocol='https',
                domain='github.com',
                user='user',
                repo='repo',
                branch='branch',
                subdirs=['subdir','subsubdir']
            )
        ),
        (
            'https://github.com/user/repo:branch/subdir/subsubdir/',
            Location(
                protocol='https',
                domain='github.com',
                user='user',
                repo='repo',
                branch='branch',
                subdirs=['subdir','subsubdir']
            )
        ),
        (
            'https://x-access-token:AccessToken@github.com/user/repo:branch',
            Location(
                protocol='https',
                access='x-access-token:AccessToken',
                domain='github.com',
                user='user',
                repo='repo',
                branch='branch',
            )
        ),
        (
            'git@github.com/user/repo:branch',
            Location(
                protocol='git',
                domain='github.com',
                user='user',
                repo='repo',
                branch='branch'
            )
        ),
        (
            'git@github.com/user/repo:branch/',
            Location(
                protocol='git',
                domain='github.com',
                user='user',
                repo='repo',
                branch='branch'
            )
        ),
        (
            'git@github.com/user/repo:branch/subdir',
            Location(
                protocol='git',
                domain='github.com',
                user='user',
                repo='repo',
                branch='branch',
                subdirs=['subdir']
            )
        ),
        (
            'git@github.com/user/repo:branch/subdir/',
            Location(
                protocol='git',
                domain='github.com',
                user='user',
                repo='repo',
                branch='branch',
                subdirs=['subdir']
            )
        ),
        (
            'git@github.com/user/repo:branch/subdir/subsubdir',
            Location(
                protocol='git',
                domain='github.com',
                user='user',
                repo='repo',
                branch='branch',
                subdirs=['subdir','subsubdir']
            )
        ),
        (
            'git@github.com/user/repo:branch/subdir/subsubdir/',
            Location(
                protocol='git',
                domain='github.com',
                user='user',
                repo='repo',
                branch='branch',
                subdirs=['subdir','subsubdir']
            )
        ),
    ]
)
def test_location(location, expected):
    loc = ParseLocation(location)

    print(f"""\
protocol: {loc.protocol} {expected.protocol}
access: {loc.access} {expected.access}
domain: {loc.domain} {expected.domain}
user: {loc.user} {expected.user}
repo: {loc.repo} {expected.repo}
branch: {loc.branch} {expected.branch}
subdirs: {loc.subdirs} {expected.subdirs}\
""")

    assert loc == expected
