name: 'BuildTheDocs GitHub Action'
description: 'Build and publish Sphinx sites to GitHub Pages'
inputs:
  config:
    description: 'YAML configuration file'
    default: '.btd.yml'
  token:
    description: 'Token to make authenticated API calls; can be passed in using {{ secrets.GITHUB_TOKEN }}'
runs:
  using: 'docker'
  image: 'Dockerfile'
