name: 'doc'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 5'

env:
  CI: true

jobs:

  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        ./btd.sh build -d -v "master,demo"
        #./btd.sh deploy
      env:
        GH_DEPKEY: ${{ secrets.GH_DEPKEY }}
        GH_SHA:    ${{ github.sha }}
