name: 'images'

on:
  push:
    paths:
      - '.github/workflows/images.yml'
      - 'images/*'
  schedule:
    - cron: '0 0 * * 5'

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:

  multi:
    strategy:
      fail-fast: false
      matrix:
        file: [ sphinx, latex, hugo ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./images/build.sh "${{ matrix.file }}.dockerfile"
    - name: docker push
      run: |
        echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
        set +e
        for img in `echo $(docker images btdi/* | awk -F ' ' '{print $1 ":" $2}') | cut -d ' ' -f2-`; do
          docker push "$img"
        done
        docker logout

  single:
    strategy:
      fail-fast: false
      matrix:
        file: [ btd, dev, bookdown ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t btdi/${{ matrix.file }} . -f- < images/${{ matrix.file }}.dockerfile
    - name: docker push
      run: |
        echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
        set +e
        docker push btdi/${{ matrix.file }}
        docker logout
