name: 'images'

on:
  push:
    paths:
      - '.github/workflows/images.yml'
      - 'images/*'
      - 'ci.sh'
  schedule:
    - cron: '0 0 * * 5'

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:

  imgs:
    strategy:
      fail-fast: false
      matrix:
        file: [ sphinx, latex, hugo ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ./ci.sh "Dockerfile.${{ matrix.file }}"
    - name: docker push
      run: |
        echo "${{ secrets.DOCKER_PASS }}" |\
        docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

        set +e

        for img in `echo $(docker images btdi/* | awk -F ' ' '{print $1 ":" $2}') | cut -d ' ' -f2-`; do
          docker push "$img"
        done

        docker logout

  dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: docker build -t btdi/dev - < images/Dockerfile.dev
    - name: docker push
      run: |
        echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
        set +e
        docker push btdi/dev
        docker logout
