name: 'images'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 5'

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        file: [ btd, dev ]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Build
      run: docker build -t btdi/${{ matrix.file }} . -f- < images/${{ matrix.file }}.dockerfile

    - name: Push
      if: github.event_name != 'pull_request'
      run: |
        echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
        set +e
        docker push btdi/${{ matrix.file }}
        docker logout
